require("SKL");
setI18nR(false,'item','iron-plate','exotic');
setI18nR(false,'item','steel-plate','exotic');
setI18nR(false,'item','copper-plate','exotic');
setI18nR(false,'recipe','iron-plate','exotic');
setI18nR(false,'recipe','steel-plate','exotic');
setI18nR(false,'recipe','copper-plate','exotic');
setI18n(true,'lab','biolab','entity','exotic');
setI18n(true,'reactor','nuclear-reactor','entity','exotic');