require("SKL");

setI18nR(true,'item','automation-science-pack','sci');
setI18nR(true,'item','bob-advanced-logistic-science-pack','sci');
setI18nR(true,'item','lab','sci');
setI18nR(true,'item','logistic-science-pack','sci');
setI18nR(true,'item','chemical-science-pack','sci');
setI18nR(true,'item','military-science-pack','sci');
setI18nR(true,'item','production-science-pack','sci');
setI18nR(true,'item','utility-science-pack','sci');
setI18nR(true,'technology','alien-science-pack','sci');
setI18nR(true,'technology','omnipack-technology','sci');
setI18nR(true,'technology','science-pack-gold','sci');
setI18nR(true,'technology','bob-advanced-logistic-science-pack','sci');
setI18nR(true,'technology','logistic-science-pack','sci');
setI18nR(true,'technology','chemical-science-pack','sci');
setI18nR(true,'technology','military-science-pack','sci');
setI18nR(true,'technology','production-science-pack','sci');
setI18nR(true,'technology','utility-science-pack','sci');